/* Engine error message table (bilingual EN/ZH). Enum order maps 1:1 to LZErr in err.h. */
#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "err.h"

static const char *const LZ_ERR_EN[LZ_ERR_COUNT] = {
    [LZ_ERR_OK]          = "ok",
    [LZ_ERR_OPEN_FILE]   = "cannot open file: %s",
    [LZ_ERR_FSEEK]       = "fseek failed: %s",
    [LZ_ERR_EMPTY_FILE]  = "empty or invalid file: %s",
    [LZ_ERR_ALLOC]       = "out of memory (need %ld bytes: %s)",
    [LZ_ERR_READ_SHORT]  = "short read: got %lu / %ld bytes",
    [LZ_ERR_NULL_ARG]    = "null argument",
    [LZ_ERR_STATE_ALLOC] = "runtime state allocation failed",
    [LZ_ERR_LAYERS_ALLOC] = "layer array allocation failed",
    [LZ_ERR_CLAIM_ALLOC] = "claim table allocation failed",
    [LZ_ERR_SEQ_LEN]     = "seq_len must be positive",
    [LZ_ERR_CANCELLED]   = "stopped at the caller's request",
    [LZ_ERR_LFN_NOT_FOUND] = "cannot find %s in %s (neither the long name "
                             "nor an 8.3 short form)",
    [LZ_ERR_LFN_AMBIGUOUS] = "%s: %d files here share one 8.3 short name; "
                             "rename so that only one matches",
    [LZ_ERR_SAMPLER_INIT] = "sampler init failed",
    [LZ_ERR_PROMPT_BUF]  = "prompt buffer allocation failed",
    [LZ_ERR_PROMPT_ENCODE] = "prompt encode failed",
    [LZ_ERR_PROMPT_LONG] = "prompt too long: %d tokens, limit %d",
    [LZ_ERR_STOP_LONG]   = "stop string exceeds %d-byte limit",
    [LZ_ERR_FORWARD]     = "forward failed (token/position out of range)",
    [LZ_ERR_CKPT_EMPTY]  = "checkpoint has never been saved into",
    [LZ_ERR_CKPT_STALE]  = "checkpoint is stale: the run state was reset or reallocated after it was saved, so the KV cache it relies on no longer holds that prefix",
    [LZ_ERR_CKPT_SHAPE]  = "checkpoint does not match this model's shapes",
    [LZ_ERR_SPEC_NO_HEAD] = "speculative decoding requested (spec_k > 0) but the model has no MTP head bound",
    [LZ_ERR_SPEC_K_RANGE] = "spec_k %d out of range 1..%d",
    [LZ_ERR_LOOK_W_RANGE] = "lookahead width %d out of range 1..%d",
    [LZ_ERR_LOOK_D_RANGE] = "lookahead depth %d out of range 1..%d",
    [LZ_ERR_NET_INIT]    = "socket stack init failed",
    [LZ_ERR_NET_PORT]    = "invalid port %d (1-65535)",
    [LZ_ERR_NET_SOCKET]  = "socket() failed (code %d)",
    [LZ_ERR_NET_BIND]    = "cannot bind 127.0.0.1:%d (code %d) - already in use?",
    [LZ_ERR_NET_LISTEN]  = "listen() failed (code %d)",
    [LZ_ERR_NET_ACCEPT]  = "accept() failed (code %d)",
    [LZ_ERR_JSON_ALLOC]  = "JSON buffer allocation failed (%lu bytes)",
    [LZ_ERR_JSON_ROOT]   = "JSON root parse failed",
    [LZ_ERR_JSON_TRAIL]  = "trailing content after JSON root",
    [LZ_ERR_CFG_ROOT]    = "config.json root is not an object",
    [LZ_ERR_CFG_LAYER_TYPES] = "config missing layer_types",
    [LZ_ERR_CFG_LAYER_LEN] = "layer_types length %d != num_hidden_layers %d",
    [LZ_ERR_CFG_LAYER_RANGE] = "layer count %d out of range 1..%d",
    [LZ_ERR_CFG_LAYER_TYPE] = "unrecognized layer type at %d: %s",
    [LZ_ERR_CFG_FIELDS]  = "config key fields missing or invalid (vocab=%d hidden=%d head_dim=%d inter=%d)",
    [LZ_ERR_CFG_HEADS]   = "invalid attention heads: n_heads=%d n_kv_heads=%d",
    [LZ_ERR_CFG_ROTARY]  = "invalid rotary_dim=%d (head_dim=%d, factor=%g)",
    [LZ_ERR_CFG_ROPE_SCALING] = "unsupported rope_scaling type: %s",
    [LZ_ERR_CFG_KDA_ACT] = "kda_gate_activation must be silu, got %s",
    [LZ_ERR_CFG_MOE_FIELDS] = "invalid MoE fields: num_experts=%d top_k=%d first_k_dense_replace=%d",
    [LZ_ERR_TENSOR_MISSING] = "missing tensor %s",
    [LZ_ERR_TENSOR_DIMS] = "tensor %s dim mismatch: want %d dims, got %d",
    [LZ_ERR_TENSOR_SHAPE] = "tensor %s dim %d mismatch: want %lld, got %lld",
    [LZ_ERR_PREFIX]      = "embed_tokens.weight not found; cannot detect prefix",
    [LZ_ERR_UNCLAIMED]   = "tensor %s unclaimed by any spec; arch gap?",
    [LZ_ERR_MTP_LAYERS]  = "mtp_num_hidden_layers is %d; only 0 or 1 supported",
    [LZ_ERR_TENSOR_ALLOC] = "tensor %s allocation failed",
    [LZ_ERR_TENSOR_ALLOC_BYTES] = "tensor %s allocation failed (need %lld bytes)",
    [LZ_ERR_TENSOR_READ] = "tensor %s read failed (truncated)",
    [LZ_ERR_TENSOR_ELEMS] = "tensor %s elem count mismatch: want %lld, file %u",
    [LZ_ERR_TENSOR_GS]   = "tensor %s invalid group size",
    [LZ_ERR_TENSOR_DTYPE] = "tensor %s invalid dtype %u",
    [LZ_ERR_NOT_OPEN]    = "model not open",
    [LZ_ERR_BIN_OPEN]    = "cannot open %s",
    [LZ_ERR_BIN_CFG_READ] = "config read failed (truncated)",
    [LZ_ERR_BIN_MAGIC]   = "not a model.bin (bad magic)",
    [LZ_ERR_BIN_VERSION] = "unsupported model.bin version %u",
    [LZ_ERR_BIN_PAD]     = "nonzero layer_types padding",
    [LZ_ERR_BIN_CFG]     = "model.bin config invalid",
    [LZ_ERR_TK_ROOT]     = "tokenizer.json root is not an object",
    [LZ_ERR_TK_MODEL]    = "missing model object",
    [LZ_ERR_TK_TYPE]     = "unsupported tokenizer type (need BPE)",
    [LZ_ERR_TK_VOCAB]    = "missing model.vocab",
    [LZ_ERR_TK_MERGES]   = "missing model.merges",
    [LZ_ERR_TK_ID_RANGE] = "vocab id %d out of range",
    [LZ_ERR_TK_ID_DUP]   = "duplicate vocab id %d",
    [LZ_ERR_TK_WORD]     = "word %d cannot be restored to bytes",
    [LZ_ERR_TK_ID_MISSING] = "vocab missing id %d",
    [LZ_ERR_TK_MERGE_PAIR] = "merges[%d] is not a string pair",
    [LZ_ERR_TK_MERGE_FULL] = "merges hash table full",
    [LZ_ERR_TK_MERGE_LONG] = "merges[%d] side exceeds %d codepoints",
    [LZ_ERR_ST_NOT_FOUND] = "file missing or too small: %s",
    [LZ_ERR_ST_OPEN] = "cannot open: %s",
    [LZ_ERR_ST_HEADER_LEN] = "read header length failed",
    [LZ_ERR_ST_HEADER_BAD] = "header length unreasonable: %llu (file %lld bytes)",
    [LZ_ERR_ST_HEADER_ALLOC] = "header buffer allocation failed: %llu bytes",
    [LZ_ERR_ST_HEADER_READ] = "header read incomplete",
    [LZ_ERR_ST_HEADER_JSON] = "header is not a JSON object",
    [LZ_ERR_ST_NO_TENSORS] = "no tensors in file",
    [LZ_ERR_ST_TENSOR_ALLOC] = "tensor table allocation failed",
    [LZ_ERR_ST_DESC] = "tensor %s description is not an object",
    [LZ_ERR_ST_SHAPE] = "tensor %s invalid shape",
    [LZ_ERR_ST_SHAPE_MISSING] = "tensor %s missing shape",
    [LZ_ERR_ST_DIMS] = "tensor %s too many dims: %d",
    [LZ_ERR_ST_DTYPE] = "tensor %s unknown dtype: %s",
    [LZ_ERR_ST_DTYPE_F32] = "tensor %s dtype %s cannot convert to f32",
    [LZ_ERR_ST_OFFSET] = "tensor %s invalid data_offsets",
    [LZ_ERR_ST_OFFSET_RANGE] = "tensor %s invalid data_offsets range",
    [LZ_ERR_ST_SEEK] = "seek tensor %s failed (offset %llu, beyond platform addressing?)",
    [LZ_ERR_ST_OVERFLOW] = "tensor %s data beyond end of file",
    [LZ_ERR_ST_ELEMS] = "tensor %s element count mismatch: want %lld, got %lld",
    [LZ_ERR_ST_READ] = "tensor %s read incomplete",
    [LZ_ERR_ST_NBYTES] = "tensor %s byte count mismatch: declared %llu, shape %lld",
    [LZ_ERR_ST_DATA_SIZE] = "data area size mismatch: %llu + %llu != %lld",
    [LZ_ERR_ST_NULL] = "lz_st_read_f32 null argument",
    [LZ_ERR_OOM] = "out of memory",
    [LZ_ERR_ST_NULL2] = "lz_st_read_raw null argument",
    [LZ_ERR_JSON_PARSE]    = "JSON parse failed at offset %ld: %s",
    [LZ_ERR_JSON_BAD_ESC]  = "bad \\u escape",
    [LZ_ERR_JSON_ESC_TRUNC] = "string truncated after escape",
    [LZ_ERR_JSON_STR_UNTERM] = "unterminated string",
    [LZ_ERR_JSON_COLON]    = "object member missing colon",
    [LZ_ERR_JSON_OBJ_END]  = "object missing comma or right brace",
    [LZ_ERR_JSON_DEPTH]    = "nesting too deep",
    [LZ_ERR_JSON_NUM]      = "bad number format",
    [LZ_ERR_JSON_ARR_END]  = "array missing comma or right bracket",
    [LZ_ERR_JSON_VALUE]    = "unrecognized value",
    [LZ_ERR_JSON_EXPECT_STR] = "expected string",
    [LZ_ERR_JSON_ESC]      = "unknown escape character",
    [LZ_ERR_JSON_NODE_ALLOC] = "node array allocation failed",
    [LZ_ERR_JSON_EOF]      = "unexpected end of input",
    [LZ_ERR_JSON_LITERAL]  = "invalid literal",
    [LZ_ERR_OUT_BUF]     = "output buffer is null",
    [LZ_ERR_NO_MESSAGES] = "no messages",
    [LZ_ERR_NO_USER]     = "no user turn in messages",
    [LZ_ERR_SYSTEM_FIRST] = "system message must come first",
    [LZ_ERR_ROLE]        = "unknown message role: %d",
    [LZ_ERR_RENDER_ALLOC] = "render buffer allocation failed",
    [LZ_ERR_TRUNC]        = "output buffer too small: need %d bytes",
    [LZ_ERR_HIST_FULL]    = "conversation history full (%d turns)",
    [LZ_ERR_HIST_ALLOC]   = "history turn allocation failed",
    [LZ_ERR_CPU_NO_CPUID] = "this processor has no CPUID instruction, so "
                            "llama98 cannot tell what it supports. A "
                            "Pentium-class processor (Socket 7) or newer "
                            "is required.",
    [LZ_ERR_CPU_NO_FPU]   = "this processor has no floating-point unit. "
                            "llama98 needs one - a 486DX, a Pentium, or "
                            "anything newer.",
    [LZ_ERR_INTERNAL]     = "internal error",
};

static const char *const LZ_ERR_ZH[LZ_ERR_COUNT] = {
    [LZ_ERR_OK]          = "成功",
    [LZ_ERR_OPEN_FILE]   = "无法打开文件: %s",
    [LZ_ERR_FSEEK]       = "fseek 失败: %s",
    [LZ_ERR_EMPTY_FILE]  = "文件为空或大小无效: %s",
    [LZ_ERR_ALLOC]       = "内存不足，需要 %ld 字节: %s",
    [LZ_ERR_READ_SHORT]  = "读取不完整: 得到 %lu / %ld 字节",
    [LZ_ERR_NULL_ARG]    = "参数为空",
    [LZ_ERR_STATE_ALLOC] = "运行时状态内存分配失败",
    [LZ_ERR_LAYERS_ALLOC] = "层数组内存不足",
    [LZ_ERR_CLAIM_ALLOC] = "认领表内存不足",
    [LZ_ERR_SEQ_LEN]     = "seq_len 必须为正",
    /* (want, dir), as in the English: Watcom's C runtime has no
       positional %1$s, so the wording takes them in arrival order. */
    [LZ_ERR_CANCELLED]   = "已按请求停止",
    [LZ_ERR_LFN_NOT_FOUND] = "找不到 %s（目录: %s；长名和 8.3 短名都没有）",
    [LZ_ERR_LFN_AMBIGUOUS] = "%s: 此目录下有 %d 个文件的 8.3 短名相同，"
                             "请重命名使其唯一",
    [LZ_ERR_SAMPLER_INIT] = "采样器初始化失败",
    [LZ_ERR_PROMPT_BUF]  = "prompt 缓冲分配失败",
    [LZ_ERR_PROMPT_ENCODE] = "prompt 编码失败",
    [LZ_ERR_PROMPT_LONG] = "prompt 过长: %d token，上限 %d",
    [LZ_ERR_STOP_LONG]   = "停止串超过 %d 字节上限",
    [LZ_ERR_FORWARD]     = "前向失败（token/位置越界）",
    [LZ_ERR_CKPT_EMPTY]  = "检查点尚未保存过",
    [LZ_ERR_CKPT_STALE]  = "检查点已失效：保存后运行状态被重置或重新分配，它依赖的 KV 缓存已不再持有那段前缀",
    [LZ_ERR_CKPT_SHAPE]  = "检查点与当前模型的形状不符",
    [LZ_ERR_SPEC_NO_HEAD] = "请求了投机解码（spec_k > 0）但模型未绑定 MTP 头",
    [LZ_ERR_SPEC_K_RANGE] = "spec_k %d 超出范围 1..%d",
    [LZ_ERR_LOOK_W_RANGE] = "前瞻宽度 %d 超出范围 1..%d",
    [LZ_ERR_LOOK_D_RANGE] = "前瞻深度 %d 超出范围 1..%d",
    [LZ_ERR_NET_INIT]    = "套接字子系统初始化失败",
    [LZ_ERR_NET_PORT]    = "端口 %d 无效（1-65535）",
    [LZ_ERR_NET_SOCKET]  = "socket() 失败（代码 %d）",
    [LZ_ERR_NET_BIND]    = "无法绑定 127.0.0.1:%d（代码 %d）——端口被占用？",
    [LZ_ERR_NET_LISTEN]  = "listen() 失败（代码 %d）",
    [LZ_ERR_NET_ACCEPT]  = "accept() 失败（代码 %d）",
    [LZ_ERR_JSON_ALLOC]  = "JSON 缓冲区内存不足（%lu 字节）",
    [LZ_ERR_JSON_ROOT]   = "JSON 根节点解析失败",
    [LZ_ERR_JSON_TRAIL]  = "JSON 根值之后存在多余内容",
    [LZ_ERR_CFG_ROOT]    = "config.json 根不是对象",
    [LZ_ERR_CFG_LAYER_TYPES] = "config 缺少 layer_types",
    [LZ_ERR_CFG_LAYER_LEN] = "layer_types 长度 %d 与 num_hidden_layers %d 不符",
    [LZ_ERR_CFG_LAYER_RANGE] = "层数 %d 超出支持范围 1..%d",
    [LZ_ERR_CFG_LAYER_TYPE] = "第 %d 层的类型无法识别: %s",
    [LZ_ERR_CFG_FIELDS]  = "config 关键字段缺失或非法（vocab=%d hidden=%d head_dim=%d inter=%d）",
    [LZ_ERR_CFG_HEADS]   = "注意力头数非法：n_heads=%d n_kv_heads=%d",
    [LZ_ERR_CFG_ROTARY]  = "rotary_dim=%d 非法（head_dim=%d, factor=%g）",
    [LZ_ERR_CFG_ROPE_SCALING] = "不支持的 rope_scaling 类型: %s",
    [LZ_ERR_CFG_KDA_ACT] = "kda_gate_activation 必须是 silu，实际为 %s",
    [LZ_ERR_CFG_MOE_FIELDS] = "MoE 字段非法：num_experts=%d top_k=%d first_k_dense_replace=%d",
    [LZ_ERR_TENSOR_MISSING] = "缺少张量 %s",
    [LZ_ERR_TENSOR_DIMS] = "张量 %s 维数不符：期望 %d 维，实际 %d 维",
    [LZ_ERR_TENSOR_SHAPE] = "张量 %s 第 %d 维不符：期望 %lld，实际 %lld",
    [LZ_ERR_PREFIX]      = "找不到 embed_tokens.weight，无法确定张量名前缀",
    [LZ_ERR_UNCLAIMED]   = "张量 %s 未被任何规格认领，架构理解可能有缺口",
    [LZ_ERR_MTP_LAYERS]  = "mtp_num_hidden_layers 为 %d，只支持 0 或 1",
    [LZ_ERR_TENSOR_ALLOC] = "张量 %s 内存不足",
    [LZ_ERR_TENSOR_ALLOC_BYTES] = "张量 %s 内存不足（需要 %lld 字节）",
    [LZ_ERR_TENSOR_READ] = "张量 %s 读取失败（文件截断）",
    [LZ_ERR_TENSOR_ELEMS] = "张量 %s 元素数不符：期望 %lld，文件 %u",
    [LZ_ERR_TENSOR_GS]   = "张量 %s 组大小非法",
    [LZ_ERR_TENSOR_DTYPE] = "张量 %s dtype %u 非法",
    [LZ_ERR_NOT_OPEN]    = "模型尚未 open",
    [LZ_ERR_BIN_OPEN]    = "无法打开 %s",
    [LZ_ERR_BIN_CFG_READ] = "config 读取失败（文件截断）",
    [LZ_ERR_BIN_MAGIC]   = "不是 model.bin（magic 不符）",
    [LZ_ERR_BIN_VERSION] = "不支持的 model.bin 版本 %u",
    [LZ_ERR_BIN_PAD]     = "layer_types 尾部填充非零",
    [LZ_ERR_BIN_CFG]     = "model.bin config 非法",
    [LZ_ERR_TK_ROOT]     = "tokenizer.json 根不是对象",
    [LZ_ERR_TK_MODEL]    = "缺少 model 对象",
    [LZ_ERR_TK_TYPE]     = "不支持的 tokenizer 类型（需 BPE）",
    [LZ_ERR_TK_VOCAB]    = "缺少 model.vocab",
    [LZ_ERR_TK_MERGES]   = "缺少 model.merges",
    [LZ_ERR_TK_ID_RANGE] = "vocab id %d 越界",
    [LZ_ERR_TK_ID_DUP]   = "vocab id %d 重复",
    [LZ_ERR_TK_WORD]     = "词条 %d 无法还原字节",
    [LZ_ERR_TK_ID_MISSING] = "vocab 缺少 id %d",
    [LZ_ERR_TK_MERGE_PAIR] = "merges[%d] 不是字符串对",
    [LZ_ERR_TK_MERGE_FULL] = "merges 哈希表溢出",
    [LZ_ERR_TK_MERGE_LONG] = "merges[%d] 单边超过 %d 个码点",
    [LZ_ERR_ST_NOT_FOUND] = "文件不存在或过小: %s",
    [LZ_ERR_ST_OPEN] = "无法打开: %s",
    [LZ_ERR_ST_HEADER_LEN] = "读取头长度失败",
    [LZ_ERR_ST_HEADER_BAD] = "头长度不合理: %llu（文件 %lld 字节）",
    [LZ_ERR_ST_HEADER_ALLOC] = "头部缓冲内存不足: %llu 字节",
    [LZ_ERR_ST_HEADER_READ] = "头部读取不完整",
    [LZ_ERR_ST_HEADER_JSON] = "头部不是 JSON 对象",
    [LZ_ERR_ST_NO_TENSORS] = "文件中没有张量",
    [LZ_ERR_ST_TENSOR_ALLOC] = "张量表内存不足",
    [LZ_ERR_ST_DESC] = "张量 %s 的描述不是对象",
    [LZ_ERR_ST_SHAPE] = "张量 %s 的形状非法",
    [LZ_ERR_ST_SHAPE_MISSING] = "张量 %s 缺少 shape",
    [LZ_ERR_ST_DIMS] = "张量 %s 维度过多: %d",
    [LZ_ERR_ST_DTYPE] = "张量 %s 的 dtype 无法识别: %s",
    [LZ_ERR_ST_DTYPE_F32] = "张量 %s 的 dtype %s 无法转为 f32",
    [LZ_ERR_ST_OFFSET] = "张量 %s 的 data_offsets 非法",
    [LZ_ERR_ST_OFFSET_RANGE] = "张量 %s 的 data_offsets 区间非法",
    [LZ_ERR_ST_SEEK] = "定位张量 %s 失败（偏移 %llu，可能超出本平台寻址能力）",
    [LZ_ERR_ST_OVERFLOW] = "张量 %s 的数据超出文件末尾",
    [LZ_ERR_ST_ELEMS] = "张量 %s 元素数不符：期望 %lld，实际 %lld",
    [LZ_ERR_ST_READ] = "读取张量 %s 不完整",
    [LZ_ERR_ST_NBYTES] = "张量 %s 字节数不符：声明 %llu，按 shape 应为 %lld",
    [LZ_ERR_ST_DATA_SIZE] = "数据区大小与文件不符：%llu + %llu != %lld",
    [LZ_ERR_ST_NULL] = "lz_st_read_f32 参数为空",
    [LZ_ERR_OOM] = "内存不足",
    [LZ_ERR_ST_NULL2] = "lz_st_read_raw 参数为空",
    [LZ_ERR_JSON_PARSE]    = "JSON 解析失败（偏移 %ld）：%s",
    [LZ_ERR_JSON_BAD_ESC]  = "\\u 转义格式错误",
    [LZ_ERR_JSON_ESC_TRUNC] = "字符串在转义符后截断",
    [LZ_ERR_JSON_STR_UNTERM] = "字符串未闭合",
    [LZ_ERR_JSON_COLON]    = "对象成员缺少冒号",
    [LZ_ERR_JSON_OBJ_END]  = "对象缺少逗号或右花括号",
    [LZ_ERR_JSON_DEPTH]    = "嵌套过深",
    [LZ_ERR_JSON_NUM]      = "数字格式错误",
    [LZ_ERR_JSON_ARR_END]  = "数组缺少逗号或右方括号",
    [LZ_ERR_JSON_VALUE]    = "无法识别的值",
    [LZ_ERR_JSON_EXPECT_STR] = "期望字符串",
    [LZ_ERR_JSON_ESC]      = "未知的转义字符",
    [LZ_ERR_JSON_NODE_ALLOC] = "节点数组内存不足",
    [LZ_ERR_JSON_EOF]      = "输入意外结束",
    [LZ_ERR_JSON_LITERAL]  = "非法字面量",
    [LZ_ERR_OUT_BUF]     = "输出缓冲为空",
    [LZ_ERR_NO_MESSAGES] = "没有传入任何消息",
    [LZ_ERR_NO_USER]     = "消息里没有用户提问",
    [LZ_ERR_SYSTEM_FIRST] = "system 消息只能排在最前面",
    [LZ_ERR_ROLE]        = "未知的消息角色: %d",
    [LZ_ERR_RENDER_ALLOC] = "渲染缓冲分配失败",
    [LZ_ERR_TRUNC]        = "输出缓冲区太小: 需要 %d 字节",
    [LZ_ERR_HIST_FULL]    = "对话历史已满 (%d 轮)",
    [LZ_ERR_HIST_ALLOC]   = "历史轮次分配失败",
    [LZ_ERR_CPU_NO_CPUID] = "这颗处理器没有 CPUID 指令，llama98 无法判断它"
                            "支持什么。需要奔腾级（Socket 7）或更新的处理器。",
    [LZ_ERR_CPU_NO_FPU]   = "这颗处理器没有浮点单元，而 llama98 需要它。"
                            "486DX、奔腾或更新的处理器都可以。",
    [LZ_ERR_INTERNAL]     = "内部错误",
};

static int g_english = 1;   /* default English */

void lz_set_error_lang(int english) {
    g_english = english ? 1 : 0;
}

int lz_error_lang(void) {
    return g_english;
}

const char *lz_err_text(LZErr code) {
    if (code < 0 || code >= LZ_ERR_COUNT) code = LZ_ERR_COUNT - 1;
    return g_english ? LZ_ERR_EN[code] : LZ_ERR_ZH[code];
}

int lz_err_fmt(char *buf, int len, LZErr code, ...) {
    va_list ap;
    int n;
    va_start(ap, code);
    n = lz_err_fmt_v(buf, len, code, ap);
    va_end(ap);
    return n;
}

int lz_err_fmt_v(char *buf, int len, LZErr code, va_list ap) {
    const char *fmt;
    int n;

    if (!buf || len <= 0) return -1;
    if (code < 0 || code >= LZ_ERR_COUNT) code = LZ_ERR_COUNT - 1;
    fmt = g_english ? LZ_ERR_EN[code] : LZ_ERR_ZH[code];
    n = vsnprintf(buf, (size_t)len, fmt, ap);
    return n;
}
